"""empty message

Revision ID: 991a94b1e5b7
Revises: 
Create Date: 2021-11-12 17:21:06.383180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991a94b1e5b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('_is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
